version: '3.4'
services:
  openeo-base:
    build: ./base
    image: openeo-base
    container_name: openeo-base
    command: echo
    network_mode: none

  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: openeo-rabbitmq
    hostname: rabbitmq
    env_file:
      - ./envs/rabbitmq.env
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  jobs_db:
    image: postgres
    container_name: openeo-jobs-db
    restart: always
    hostname: jobs_db
    volumes:
      - /srv/openeo/data/jobs_db_data:/var/lib/postgresql/data
    env_file:
      - ./envs/jobs.env

  processes_db:
      image: postgres
      container_name: openeo-processes-db
      restart: always
      hostname: processes_db
      volumes:
        - /srv/openeo/data/processes_db_data:/var/lib/postgresql/data
      env_file:
        - ./envs/processes.env

  openeo-gateway:
    image: openeo-gateway
    build: ./gateway
    container_name: openeo-gateway
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-base
    env_file:
      - ./envs/rabbitmq.env
      - ./envs/gateway.env
      - ./envs/oidc.env
    volumes:
      - ./gateway:/usr/src/app
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: $VIRTUAL_PORT
      LETSENCRYPT_HOST: $VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      LETSENCRYPT_TEST: $LETSENCRYPT_TEST
    ports:
      - 3000:3000

  openeo-data:
    build: ./services/data
    image: openeo-data
    container_name: openeo-data
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-gateway
      - openeo-base
    env_file:
      - ./envs/rabbitmq.env
      - ./envs/data.env
    environment:
      CACHE_PATH: /usr/src/cache
    volumes:
      - eo-discovery-cache:/usr/src/cache
      - ./services/data:/usr/src/app

  openeo-processes:
    build: ./services/processes
    image: openeo-processes
    container_name: openeo-processes
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-gateway
      - processes_db
      - openeo-base
    env_file:
      - ./envs/rabbitmq.env
      - ./envs/processes.env
    environment:
      PROCESS_API_DIR: /usr/src/api
    volumes:
      - process-api-data:/usr/src/api
      - ./services/processes:/usr/src/app

  openeo-jobs:
    build: ./services/jobs
    image: openeo-jobs
    container_name: openeo-jobs
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-gateway
      - jobs_db
      - openeo-base
    env_file:
      - ./envs/rabbitmq.env
      - ./envs/jobs.env
    volumes:
      - ./services/jobs:/usr/src/app

networks:
  default:
    external:
      name: ${PROJECT_NAME}_proxy

volumes:
  process-api-data:
  eo-discovery-cache:

    # Set up connection(s) to job scheduler(s) (Airflow, Dask, etc...)
