version: '3.4'
services:
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672

  jobs_db:
    ports:
      - 5433:5432

  processes_db:
    ports:
      - 5434:5432

  users_db:
    ports:
      - 5435:5432

networks:
  default:
    external:
      name: ${PROJECT_NAME}-${OPENEO_VERSION}
