version: '3.4'
services:
  openeo-base:
    build: ./base
    image: openeo-base
    container_name: openeo-base
    command: echo
    network_mode: none

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: openeo-rabbitmq
    hostname: rabbitmq
    env_file:
      - ./envs/rabbitmq.env
    ports:
      - 5672:5672
      - 15672:15672

  jobs_db:
    image: postgres
    container_name: openeo-jobs-db
    restart: always
    hostname: jobs_db
    volumes:
      - /srv/openeo/data/jobs_db_data:/var/lib/postgresql/data
    env_file:
      - ./envs/jobs.env

  processes_db:
      image: postgres
      container_name: openeo-processes-db
      restart: always
      hostname: processes_db
      volumes:
        - /srv/openeo/data/processes_db_data:/var/lib/postgresql/data
      env_file:
        - ./envs/processes.env

  users_db:
    image: postgres
    container_name: openeo-users-db
    restart: always
    hostname: users_db
    volumes:
        - /srv/openeo/data/users_db_data:/var/lib/postgresql/data
    env_file:
      - ./envs/users.env

  openeo-gateway:
    image: openeo-gateway
    build: ./gateway
    container_name: openeo-gateway
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-base
    env_file:
      - ./envs/rabbitmq.env
      - ./envs/gateway.env
      - ./envs/oidc.env
      - ./envs/users.env
    volumes:
      - ./gateway:/usr/src/app
      - files-data:/usr/src/files
      - $SYNC_RESULTS_FOLDER:/usr/src/sync-results
      - $LOG_DIR:/usr/src/logs
    environment:
      UPLOAD_TMP_DIR: /usr/src/files/tmp
    ports:
      - 3000:3000

  openeo-capabilities:
    build: ./services/capabilities
    image: openeo-capabilities
    container_name: openeo-capabilities
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-gateway
      - openeo-base
    env_file:
      - ./envs/rabbitmq.env
    volumes:
      - ./services/capabilities:/usr/src/app
      - $LOG_DIR:/usr/src/logs

  openeo-data:
    build: ./services/data
    image: openeo-data
    container_name: openeo-data
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-gateway
      - openeo-base
    env_file:
      - ./envs/rabbitmq.env
      - ./envs/csw.env
      - ./envs/gateway.env
    environment:
      CACHE_PATH: /usr/src/cache
    volumes:
      - eo-discovery-cache:/usr/src/cache
      - ./services/data:/usr/src/app
      - $LOG_DIR:/usr/src/logs

  openeo-processes:
    build: ./services/processes
    image: openeo-processes
    container_name: openeo-processes
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-gateway
      - processes_db
      - openeo-base
    env_file:
      - ./envs/rabbitmq.env
      - ./envs/processes.env
    environment:
      PROCESS_API_DIR: /usr/src/api
    volumes:
      - process-api-data:/usr/src/api
      - ./services/processes:/usr/src/app
      - $LOG_DIR:/usr/src/logs

  openeo-jobs:
    build: ./services/jobs
    image: openeo-jobs
    container_name: openeo-jobs
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-gateway
      - jobs_db
      - openeo-base
    env_file:
      - ./envs/rabbitmq.env
      - ./envs/jobs.env
      - ./envs/csw.env
      - ./envs/gateway.env
    environment:
      AIRFLOW_DAGS: /usr/src/dags/
      SYNC_RESULTS_FOLDER: /usr/src/sync-results
      AIRFLOW_LOG_DIR: /usr/src/logs/airflow
    volumes:
      - ./services/jobs:/usr/src/app
      - $AIRFLOW_DAGS:/usr/src/dags/
      - $SYNC_RESULTS_FOLDER:/usr/src/sync-results
      - files-data:/usr/src/files
      - $LOG_DIR:/usr/src/logs

  openeo-eodatareaders:
      build: ./services/eodatareaders_rpc
      image: openeo-eodatareaders
      container_name: openeo-eodatareaders
      restart: on-failure
      depends_on:
        - rabbitmq
        - openeo-gateway
      env_file:
        - ./envs/rabbitmq.env
        - ./envs/csw.env
        - ./envs/eodatareaders.env
      environment:
        SYNC_RESULTS_FOLDER: /usr/src/sync-results
        OPENEO_PYTHON_UDF_URL: $OPENEO_PYTHON_UDF_URL
        OPENEO_R_UDF_URL: $OPENEO_R_UDF_URL
      volumes:
          - $DATA_FOLDER:$DATA_FOLDER
          - ./services/eodatareaders_rpc:/usr/src/app
          - $SYNC_RESULTS_FOLDER:/usr/src/sync-results
          - $LOG_DIR:/usr/src/logs

  openeo-files:
    build: ./services/files
    image: openeo-files
    container_name: openeo-files
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-gateway
      - openeo-base
    env_file:
      - ./envs/rabbitmq.env
    environment:
      OPENEO_FILES_DIR: /usr/src/files
    volumes:
      - files-data:/usr/src/files
      - ./services/files:/usr/src/app
      - $LOG_DIR:/usr/src/logs

networks:
  default:
    external:
      name: ${PROJECT_NAME}_proxy

volumes:
  process-api-data:
  eo-discovery-cache:
  files-data:

# Set up connection(s) to job scheduler(s) (Airflow, Dask, etc...)
