version: '3.4'
services:
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672

  jobs_db:
    ports:
      - 5433:5432

  processes_db:
    ports:
      - 5434:5432

  users_db:
    ports:
      - 5435:5432

  openeo-gateway:
    volumes:
      - ./gateway:/usr/src/app

  openeo-users:
    volumes:
      - ./services/users:/usr/src/app

  openeo-capabilities:
    volumes:
      - ./services/capabilities:/usr/src/app

  openeo-data:
    volumes:
      - ./services/data:/usr/src/app

  openeo-processes:
    volumes:
      - ./services/processes:/usr/src/app

  openeo-jobs:
    volumes:
      - ./services/jobs:/usr/src/app

  openeo-files:
    volumes:
      - ./services/files:/usr/src/app

networks:
  default:
    external:
      name: ${PROJECT_NAME}-${OPENEO_VERSION}
