version: '3.4'
services:
  openeo-base:
    build: ./base
    image: openeo-base
    container_name: openeo-base
    command: echo
    network_mode: none

  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: openeo-rabbitmq
    hostname: rabbitmq
    env_file:
      - ./envs/rabbitmq.env
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  jobs_db:
    image: postgres
    container_name: openeo-jobs-db
    restart: always
    hostname: jobs_db
    volumes:
      - /srv/openeo/data/jobs_db_data:/var/lib/postgresql/data
    env_file:
      - ./envs/jobs_db.env

  processes_db:
      image: postgres
      container_name: openeo-processes-db
      restart: always
      hostname: processes_db
      volumes:
        - /srv/openeo/data/processes_db_data:/var/lib/postgresql/data
      env_file:
        - ./envs/processes_db.env

  openeo-gateway:
    image: openeo-gateway
    build: ./gateway
    container_name: openeo-gateway
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-base
    env_file:
      - ./envs/rabbitmq_service.env
      - ./envs/gateway.env
      - ./envs/oidc.env
    ports:
      - 3000:3000

  openeo-data:
    build: ./services/data
    image: openeo-data
    container_name: openeo-data
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-gateway
      - openeo-base
    env_file:
      - ./envs/rabbitmq_service.env
      - ./envs/data.env

  openeo-processes:
    build: ./services/processes
    image: openeo-processes
    container_name: openeo-processes
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-gateway
      - processes_db
      - openeo-base
    env_file:
      - ./envs/rabbitmq_service.env
      - ./envs/processes_service.env

  openeo-jobs:
    build: ./services/jobs
    image: openeo-jobs
    container_name: openeo-jobs
    restart: on-failure
    depends_on:
      - rabbitmq
      - openeo-gateway
      - jobs_db
      - openeo-base

    env_file:
      - ./envs/rabbitmq_service.env
      - ./envs/jobs_service.env
      
    # Set up connection(s) to job scheduler(s) (Airflow, Dask, etc...)
