### GET auth token
POST http://openeo.eodc.eu/auth/login
content-type: application/json

{
    "username": "user",
    "password": "eodcUser#1"
}

### Simple data extraction on a bbox/date-range
POST http://127.0.0.1:3000/jobs
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MjExOTY1ODUsImlhdCI6MTUxODYwNDU4NSwic3ViIjoxfQ.63S3qQzmhzo8xxICFRpg9EyoJGylLpVbI7PO019gUSw

{
  "process_graph":{
    "process_id":"min_time",
    "args":{
      "imagery":{
        "process_id":"ndvi",
        "args":{
          "imagery":{
            "process_id":"filter_daterange",
            "args":{
              "imagery":{
                "process_id":"filter_bbox",
                "args":{
                  "imagery":{
                    "product_id":"Sentinel-2A"
                  },
                  "bottom": 48.023549396,
                  "left": 15.166625977,
                  "top": 48.614027308,
                  "right": 16.793975830,
                  "srs":"EPSG:4326"
                }
              },
              "from":"2018-01-01",
              "to":"2018-01-15"
            }
          },
          "red":"B04",
          "nir":"B8A"
        }
      }
    }
  }
}

### GET Job
GET http://127.0.0.1:3000/jobs/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MjExOTY1ODUsImlhdCI6MTUxODYwNDU4NSwic3ViIjoxfQ.63S3qQzmhzo8xxICFRpg9EyoJGylLpVbI7PO019gUSw

### DELETE Job
DELETE http://127.0.0.1:3000/jobs/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MjExOTY1ODUsImlhdCI6MTUxODYwNDU4NSwic3ViIjoxfQ.63S3qQzmhzo8xxICFRpg9EyoJGylLpVbI7PO019gUSw

### Execute Job
GET http://127.0.0.1:3000/jobs/17/execute
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MjExOTY1ODUsImlhdCI6MTUxODYwNDU4NSwic3ViIjoxfQ.63S3qQzmhzo8xxICFRpg9EyoJGylLpVbI7PO019gUSw
