### Health Check
GET http://127.0.0.1:5000/health

### Simple data extraction on a bbox/date-range
POST http://127.0.0.1:5000/jobs
content-type: application/json

{
    "process_graph": {
        "process_id": "filter_daterange",
        "args": {
            "collections": [{
                "process_id": "filter_bbox",
                "args": {
                    "collections": [{
                        "product_id": "Sentinel-2A"
                    }],
                    "left" : -5,
                    "right" :5,
                    "top" : 5,
                    "bottom" : -5,
                    "srs" : "EPSG:4326"
                }
            }],
            "from": "2017-01-01",
            "to": "2017-01-03"
        }
    }
}

### UC1 Process Graph
POST http://127.0.0.1:5000/jobs
content-type: application/json

{
    "process_graph": 
    {
        "process_id": "min_time",
        "args": {
            "collections": [{
                "process_id": "NDVI",
                "args": {
                    "collections": [{
                        "process_id": "filter_daterange",
                        "args": {
                            "collections": [{
                                "process_id": "filter_bbox",
                                "args": {
                                    "collections": [{
                                        "product_id": "S2_L2A_T32TPS_20M"
                                    }],
                                    "left" : 652000,
                                    "right" :672000,
                                    "top" : 5161000,
                                    "bottom" : 5181000,
                                    "srs" : "EPSG:32632"
                                }
                            }],
                            "from": "2017-01-01",
                            "to": "2017-01-31"
                        }
                    }],
                    "red": "B04",
                    "nir": "B8A"
                }
            }]
        }
    }
}