---
kind: Template
apiVersion: v1
metadata:
  name: eodc-service-job
  annotations:
    description: EODC Job Service
    iconClass: icon-python
labels:
  service: eodc-service-job
  provider: eodc
  project: eodc-services
  version: 0.0.1

parameters:
# Service
- name: SERVICE_NAME
  displayName: Service Name
  description: Name of the service
  value: eodc-service-job
  required: true
- name: SERVICE_SETTINGS
  displayName: Service Config Setting
  description: Setting for the EODC Job Service
  value: service.config.ProductionConfig
  required: true
- name: MEMORY_LIMIT_SERVICE
  displayName: Memory Limit
  description: Maximum amount of memory the service can use.
  value: 4Gi
  required: true
- name: EXECUTION_NAMESPACE
  displayName: Job Execution Namespace
  description: Namspace of OpenSHift project for job execution (e.g. "execution-environment")
  value: 
  required: true
- name: SERVICEACCOUNT_TOKEN
  displayName: Service Account Token
  description: Permanent token of the service account in execution namespace
  value: 
  required: true
- name: STORAGE_CLASS
  displayName: Storage Class
  description: Storage class for PersitantVolumeClaims that should be used (e.g. "storage-write")
  value: 
  required: true
- name: OPENEO_API
  displayName: OpenEO API URI
  description: URI for accessing the OpenEO API (e.g. http://openeo.example.com)
  value: 
  required: true
- name: OPENSHIFT_API
  displayName: OpenShift API URI
  description: URI for accessing the OpenShift API (e.g. http://openshift.example.com)
  value: 
  required: true
- name: CSW_SERVER
  displayName: CSW Server URI
  description: URI for accessing CSW server (e.g. http://csw.example.com)
  value: 
  required: true

# GIT
- name: GIT_URI
  displayName: Git URI
  description: Git source URI for service
  value: git@git.eodc.eu:eodc-services/eodc-service-job.git
  required: true
- name: GIT_REF
  displayName: Git Reference
  description: Git branch/tag reference
  value: master
  required: true
- name: GIT_SECRET
  displayName: Git Secret
  description: Deployment secret for accessing GitLab
  value: eodc-builder
  required: true
- name: GITLAB_SECRET
  displayName: Gitlab Trigger Secret
  description: Secret for Gitlab trigger hock
  from: "[a-zA-Z0-9]{10}"
  generate: expression
  required: true

# POSTGRES
- name: POSTGRESQL_USER
  displayName: PostgreSQL Connection Username
  description: Username for PostgreSQL user that will be used for accessing the database.
  generate: expression
  from: user[A-Z0-9]{3}
  required: true
- name: POSTGRESQL_PASSWORD
  displayName: PostgreSQL Connection Password
  description: Password for the PostgreSQL connection user.
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true
- name: POSTGRESQL_DATABASE
  displayName: PostgreSQL Database Name
  description: Name of the PostgreSQL database accessed.
  value: jobs
required: true
- name: POSTGRESQL_VERSION
  displayName: Version of PostgreSQL Image
  description: Version of PostgreSQL image to be used (9.2, 9.4, 9.5 or latest).
  value: '9.5'
  required: true
- name: VOLUME_CAPACITY_POSTGRES
  displayName: Volume Capacity
  description: Volume space available for Postgres data, e.g. 512Mi, 2Gi.
  value: 5Gi
  required: true
- name: MEMORY_LIMIT_POSTGRES
  displayName: Memory Limit
  description: Maximum amount of memory Postgres can use.
  value: 256Mi
 required: true

objects:

# SERVICE
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${SERVICE_NAME}"
  spec:
    dockerImageRepository:
    tags:
    - name: latest

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${SERVICE_NAME}"
  spec:
    source:
      type: Git
      git:
        uri: "${GIT_URI}"
        ref: "${GIT_REF}"
      sourceSecret:
        name: "${GIT_SECRET}"
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
    output:
      to:
        kind: ImageStreamTag
        name: "${SERVICE_NAME}:latest"
    triggers:
    - type: GitLab
      gitlab:
        secret: "${GITLAB_SECRET}"
    - type: ConfigChange
    - type: ImageChange
      imageChange:

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${SERVICE_NAME}"
    labels:
      name: "${SERVICE_NAME}"
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${SERVICE_NAME}"
        from:
          kind: ImageStreamTag
          name: "${SERVICE_NAME}:latest"
    - type: ConfigChange
    replicas: 1
    selector:
      name: "${SERVICE_NAME}"
    template:
      metadata:
        labels:
          name: "${SERVICE_NAME}"
      spec:
        containers:
        - name: "${SERVICE_NAME}"
          image: "${SERVICE_NAME}"
          ports:
          - containerPort: 5000
            protocol: TCP
          readinessProbe:
            httpGet:
              path: "/ping"
              port: 5000
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            tcpSocket:
              port: 5000
          env:
          - name: SERVICE_SETTINGS
            value: "${SERVICE_SETTINGS}"
          - name: DATABASE_URL
            value: "postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@${SERVICE_NAME}-postgres:5432/${POSTGRESQL_DATABASE}"
          resources:
            limits:
              memory: "${MEMORY_LIMIT_SERVICE}"
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: Always
          securityContext:
            capabilities:
            privileged: false
        restartPolicy: Always
        dnsPolicy: ClusterFirst

- kind: Route
  apiVersion: v1
  metadata:
    name: "openeo-jobs"
    annotations:
      description: openEO /jobs route
  spec:
    host: openeo.193.170.203.100.xip.io
    path: /jobs
    to:
      kind: Service
      name: "${SERVICE_NAME}"

- kind: Service
  apiVersion: v1
  metadata:
    name: "${SERVICE_NAME}"
    annotations:
      description: The service port
  spec:
    ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
    selector:
      name: "${SERVICE_NAME}"

# POSTGRES
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${SERVICE_NAME}-postgres"
  stringData:
    database-user: "${POSTGRESQL_USER}"
    database-password: "${POSTGRESQL_PASSWORD}"
    database-name: "${POSTGRESQL_DATABASE}"

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${SERVICE_NAME}-postgres"
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - postgresql
        from:
          kind: ImageStreamTag
          name: "postgresql:${POSTGRESQL_VERSION}"
          namespace: openshift
        lastTriggeredImage:
    - type: ConfigChange
    replicas: 1
    selector:
      name: "${SERVICE_NAME}-postgres"
    template:
      metadata:
        labels:
          name: "${SERVICE_NAME}-postgres"
      spec:
        containers:
        - name: postgresql
          image:
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                'SELECT 1'
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            tcpSocket:
              port: 5432
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: "${SERVICE_NAME}-postgres"
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${SERVICE_NAME}-postgres"
                key: database-password
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: "${SERVICE_NAME}-postgres"
                key: database-name
          resources:
            limits:
              memory: "${MEMORY_LIMIT_POSTGRES}"
          volumeMounts:
          - name: vol-${SERVICE_NAME}-postgres
            mountPath: "/var/lib/pgsql/data"
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
        volumes:
        - name: vol-${SERVICE_NAME}-postgres
          persistentVolumeClaim:
            claimName: pvc-${SERVICE_NAME}-postgres
        restartPolicy: Always
        dnsPolicy: ClusterFirst

- kind: Service
  apiVersion: v1
  metadata:
    name: "${SERVICE_NAME}-postgres"
  spec:
    ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
    selector:
      name: "${SERVICE_NAME}-postgres"

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: pvc-${SERVICE_NAME}-postgres
  spec:
    storageClassName: storage-write
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${VOLUME_CAPACITY_POSTGRES}"