openapi: 3.0.1
servers:
  url: https://openeo.eodc.eu
  description: The URL to the EODC API
  versions:
    v1.0:
      url: https://openeo.eodc.eu/v1.0
      api_version: 1.0.0
    v0.4:
      url: https://openeo.eodc.eu/v0.4
      api_version: 0.4.2

info:
  title: EODC openEO API
  version: 1.0.0
  description: 'The EODC API provides access to the EODC services and data, as well as access to the openEO endpoints.'
  contact:
    name: Luca Foresta
    url: 'https://openeo.eodc.eu'
    email: luca.foresta@eodc.eu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-backend_version: 2.0.0
  x-stac_version: 0.9.0
  x-id: '0.0.1'  # id of collections' catalogue (arbitrary number for now)
  x-production: false
  # billing?
  x-file_formats:
    input:
      - name: GTiff
        title: GeoTiff
        gis_data_types:
          - raster
    output:
      - name: GTiff
        title: GeoTiff
        gis_data_types:
          - raster
  x-udf:
    Python:
      description: The Python programming language.
      default: '3.6'
      versions:
        3.6:
          libraries:
            Numpy:
              version: x.x
            xarray:
              version: y.y
    R:
      description: The R programming language.
      default: '4.0'
      versions:
        4.0:
          libraries:
            stars:
              version: x.x

# add service types    

externalDocs:
  description: EODC API Description
  url: 'https://openeo.eodc.eu/redoc'
tags:
  - name: OpenAPI
    description: The OpenAPI specification and Tools for inspecting
  - name: Capabilities
    description: General information about the API implementation and other supported capabilities at the back-end.
  - name: EO Data Discovery
    description: Discovery of Earth observation datasets that are available at the back-end.
  - name: Process Discovery
    description: Discovery of processes that are available at the back-end.
  - name: File Management
    description: Management of user-uploaded assets and processed data.
  - name: Account Management
    description: Authentication of users.
  - name: Process Graph Management
    description: Management of stored process graphs.
  - name: Batch Job Management
    description: Management of batch processing tasks (jobs) and their results.
  - name: Secondary Services Management
    description: On-demand access to data using other web service protocols.

paths:
  # Note: all endpoints are later mapped to /endpoint/{openeo_version}
  # Two exceptions are: 
  #  - /.well-known/openeo -> no versioning allowed according to specs
  #  - /base -> maps to "/" which redirects to /.well-known/openeo (but this endpoint can do whatever we want)
  # Note that /{openeo_version} actually maps to "/" of the openEO API
  /base:
    description: >-
      This endpoint is mapped to "/", which then redirects to "/.well-known/openeo"
    get:
      responses:
        '302': successfully redirects to /.well-known/openeo
  /:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1
  /.well-known/openeo:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1.well-known~1openeo
  /file_formats:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1file_formats
  # /conformance:
  #   $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1conformance
  /udf_runtimes:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1udf_runtimes
  # /service_types:
  #   $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1service_types

  /collections:
    get:
      $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1collections
    post:
      summary: Post a request to refresh the cache
      description: >-
        The request will refresh the stored cache for all collections and each individual collection.
        \n\n **Note:** This is an extension of the EODC API!
      requestBody:
        content:
          application/json:
            schema:
              title: Collections cache refresh
              type: object
              required:
                - use_cache
              properties:
                use_cache:
                  type: boolean
      security:
        - {}
        - Bearer: []
      responses:
        '200':
          description: The cache has been refreshed
        4XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/client_error
        5XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/server_error
  /collections/{collection_id}:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1collections~1{collection_id}

  /credentials/oidc:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1credentials~1oidc
  /credentials/basic:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1credentials~1basic
  /me:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1me

  /processes:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1processes
  /process_graphs:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1process_graphs
  /process_graphs/{process_graph_id}:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1process_graphs~1{process_graph_id}
  /validation:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1validation
  /processes/{process_name}:
    put:
      summary: Creates a new process.
      description: >-
        The request will ask the back-end to create a new process using the description send in the request body.
        \n\n **Note:** This is an extension of the EODC API!
      tags:
        - Process Discovery
      requestBody:
        content:
          application/json:
            schema:
              $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1processes/get/responses/200/content/application~1json/schema/properties/processes/items
      security:
        - {}
        - Bearer: []
      responses:
        '200':
          description: The processes has been successfully created.
        4XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/client_error
        5XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/server_error

  /jobs:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1jobs
  /result:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1result
  /jobs/{job_id}:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1jobs~1{job_id}
  /jobs/{job_id}/results:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1jobs~1{job_id}~1results
  /jobs/{job_id}/estimate:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1jobs~1{job_id}~1estimate
  # /jobs/{job_id}/logs:
  #   $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1jobs~1{job_id}~1logs

  /files:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1files
  /files/{path:path}:
    $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1files~1{path}
  /downloads/{job_id}/{path}:
    parameters:
      - $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/paths/~1files
    get:
      responses:
        '200':
          description: aaa.
        4XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/client_error
        5XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/server_error
  
  /users_mng/users:
    description: >-
      **Note:** This is an extension of the EODC API!
    post:
      responses:
        '200': successfully created user on database
    delete:
      responses:
        '200': successfully deleted a user in the database
  /users_mng/user_profiles:
    description: >-
      **Note:** This is an extension of the EODC API!
    post:
      responses:
        '200': successfully created user profile on database
    delete:
      responses:
        '200': successfully deleted a profile in the database
  /users_mng/oidc_providers:
    description: >-
      **Note:** This is an extension of the EODC API!
    post:
      responses:
        '200': successfully created Identity Provider on database
    delete:
      responses:
        '200': successfully deleted a identity provider in the database
  
  /openapi:
    get:
      summary: OpenAPI v3.0.1 specification
      description: >-
        The request will return the OpenAPI v3.0.1 specification as JSON document.
        \n\n **Note:** This is an extension of the EODC API!
      tags:
        - OpenAPI
      responses:
        '200':
          description: The OpenAPI v3.0.1 specification.
        4XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/client_error
        5XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/server_error
  /redoc:
    get:
      summary: API Reference
      description: >-
        The request will return a ReDoc client that can be used to inspect the OpenAPI v3.0.1 specification.
        \n\n **Note:** This is an extension of the EODC API!
      tags:
        - OpenAPI
      responses:
        '200':
          description: Returns the ReDoc client to view the OpenAPI v3.0.1 specification.
        4XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/client_error
        5XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/server_error

  /health:
    get:
      summary: Gateway Sanity Check
      description: >-
        The request will return a 200 HTTP code if the gateway is running.
        \n\n **Note:** This is an extension of the EODC API!
      tags:
        - OpenAPI
      responses:
        '200':
          description: The gateway is running.
        4XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/client_error
        5XX:
          $ref: https://raw.githubusercontent.com/Open-EO/openeo-api/1.0.0/openapi.yaml#/components/responses/server_error
