FROM python:3.6.2

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD ./requirements_worker.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt
ADD ./worker /usr/src/app/worker

ENTRYPOINT celery -A worker worker --concurrency=5 --loglevel=info