AMQP_URI: !env_var "pyamqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_HOST}:${RABBIT_PORT}"

LOGGING:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
    filelogger:
      class: logging.handlers.RotatingFileHandler
      filename: /usr/src/logs/capabilities.log
      backupCount: 3
      maxBytes: 1000000
      formatter: default
  loggers:
    standardlog:
      handlers:
        - filelogger
  formatters:
    default:
      format: '%(asctime)s %(levelname)-3s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  root:
    level: DEBUG
    handlers: [console]
