DB_URIS:
    !env_var "jobs:Base": postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}

AMQP_URI: !env_var "pyamqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_HOST}:${RABBIT_PORT}"

LOGGING:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
    filelogger:
      class: logging.handlers.RotatingFileHandler
      filename: log.log
  loggers:
    standardlog:
      handlers:
        - filelogger
  root:
    level: DEBUG
    handlers: [console]
