version: '2.2'
services:
    redis:
        container_name: airflow-redis
        image: 'redis:latest'
        command: redis-server --requirepass ${REDIS_PASSWORD}
        networks:
             - default

    postgres:
        container_name: airflow-postgres
        image: postgres:9.6
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - /srv/airflow/postgres:/var/lib/postgresql/data/pgdata
        networks:
            - default

    webserver:
        container_name: airflow-webserver
        build:
            context: ./build
        image: openeo-eodc-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
            REDIS_PASSWORD: $REDIS_PASSWORD
            LOAD_EX: $LOAD_EX
            FERNET_KEY: $FERNET_KEY
            EXECUTOR: $EXECUTOR
            FLASK_ENV: $FLASK_ENV
        volumes:
            - $PLUGINS:/usr/local/airflow/plugins
            - $DAGS:/usr/local/airflow/dags
            - $LOG_DIR_AIRFLOW:/usr/local/airflow/logs
            - ./build/airflow_worker_process.cfg:/usr/local/airflow/airflow.cfg
        ports:
            - "8080:8080"
        # todo: --ssl_cert path --ssl_key path
        command: webserver -w 10 -d false
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        networks:
            - default

    flower:
        container_name: airflow-flower
        build:
            context: ./build
        image: openeo-eodc-airflow:1.10.9
        restart: always
        environment:
            EXECUTOR: $EXECUTOR
            REDIS_PASSWORD: $REDIS_PASSWORD
            FLASK_ENV: $FLASK_ENV
        depends_on:
            - redis
        ports:
            - "5555:5555"
        command: flower
        networks:
             - default
        volumes:
          - ./build/airflow_worker_process.cfg:/usr/local/airflow/airflow.cfg

    scheduler:
        container_name: airflow-scheduler
        build:
            context: ./build
        image: openeo-eodc-airflow:1.10.9
        restart: always
        depends_on:
            - webserver
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
            REDIS_PASSWORD: $REDIS_PASSWORD
            LOAD_EX: $LOAD_EX
            FERNET_KEY: $FERNET_KEY
            EXECUTOR: $EXECUTOR
            FLASK_ENV: $FLASK_ENV
        volumes:
            - $PLUGINS:/usr/local/airflow/plugins
            - $DAGS:/usr/local/airflow/dags
            - $LOG_DIR_AIRFLOW:/usr/local/airflow/logs
            - ./build/airflow_worker_process.cfg:/usr/local/airflow/airflow.cfg
        command: scheduler
        networks:
            - default

    worker:
        container_name: airflow-worker
        build:
            context: ./build
        image: openeo-eodc-airflow:1.10.9
        restart: always
        depends_on:
            - scheduler
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
            REDIS_PASSWORD: $REDIS_PASSWORD
            LOAD_EX: $LOAD_EX
            FERNET_KEY: $FERNET_KEY
            EXECUTOR: $EXECUTOR
            GDAL_VRT_ENABLE_PYTHON: $GDAL_VRT_ENABLE_PYTHON
            GDAL_VRT_PYTHON_TRUSTED_MODULES: $GDAL_VRT_PYTHON_TRUSTED_MODULES
            FLASK_ENV: $FLASK_ENV
            OPENEO_PYTHON_UDF_URL: $OPENEO_PYTHON_UDF_URL
            OPENEO_R_UDF_URL: $OPENEO_R_UDF_URL
        volumes:
            - $PLUGINS:/usr/local/airflow/plugins
            - $DAGS:/usr/local/airflow/dags
            - $HOST_INPUT:$CONTAINER_INPUT
            - files-data:$CONTAINER_OUTPUT
            - $LOG_DIR_AIRFLOW:/usr/local/airflow/logs
            - ./build/airflow_worker_process.cfg:/usr/local/airflow/airflow.cfg
        command: worker -q process
        networks:
            - default

    worker-sensor:
        container_name: airflow-worker-sensor
        build:
            context: ./build
        image: openeo-eodc-airflow:1.10.9
        restart: always
        depends_on:
            - scheduler
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
            REDIS_PASSWORD: $REDIS_PASSWORD
            LOAD_EX: $LOAD_EX
            FERNET_KEY: $FERNET_KEY
            EXECUTOR: $EXECUTOR
            GDAL_VRT_ENABLE_PYTHON: $GDAL_VRT_ENABLE_PYTHON
            GDAL_VRT_PYTHON_TRUSTED_MODULES: $GDAL_VRT_PYTHON_TRUSTED_MODULES
            FLASK_ENV: $FLASK_ENV
            OPENEO_PYTHON_UDF_URL: $OPENEO_PYTHON_UDF_URL
            OPENEO_R_UDF_URL: $OPENEO_R_UDF_URL
        volumes:
            - $PLUGINS:/usr/local/airflow/plugins
            - $DAGS:/usr/local/airflow/dags
            - $HOST_INPUT:$CONTAINER_INPUT
            - files-data:$CONTAINER_OUTPUT
            - $LOG_DIR_AIRFLOW:/usr/local/airflow/logs
            - ./build/airflow_worker_sensor.cfg:/usr/local/airflow/airflow.cfg
        command: worker -q sensor
        networks:
            - default
            
volumes:
  files-data:
    external:
      name: ${PROJECT_NAME}_files-data

networks:
    default:
      external:
        name: ${PROJECT_NAME}_proxy
        ## Driver options needed for OpenStack environments
        # driver: bridge
        # driver_opts:
        #     com.docker.network.driver.mtu: 1450
