version: '3.4'
services:
  redis:
    container_name: airflow-redis
    image: 'redis:latest'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - default

  postgres:
    container_name: airflow-postgres
    image: postgres:9.6
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /srv/airflow/postgres:/var/lib/postgresql/data/pgdata
    networks:
      - default

  webserver:
    container_name: airflow-webserver
    build:
      context: ./build/all
    image: openeo-airflow-all:$AIRFLOW_VERSION
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      REDIS_PASSWORD: $REDIS_PASSWORD
      LOAD_EX: $LOAD_EX
      FERNET_KEY: $FERNET_KEY
      EXECUTOR: $EXECUTOR
      FLASK_ENV: $FLASK_ENV
    volumes:
      - $PLUGINS:/usr/local/airflow/plugins
      - $AIRFLOW_DAGS:/usr/local/airflow/dags
      - $LOG_DIR_AIRFLOW:/usr/local/airflow/logs
      - ./build/all/airflow.cfg:/usr/local/airflow/airflow.cfg
    ports:
      - "8080:8080"
    # todo: --ssl_cert path --ssl_key path
    command: webserver -w 10 -d false
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - default

  flower:
    container_name: airflow-flower
    build:
      context: ./build/base
    image: openeo-airflow-base:$AIRFLOW_VERSION
    restart: always
    environment:
      EXECUTOR: $EXECUTOR
      REDIS_PASSWORD: $REDIS_PASSWORD
      FLASK_ENV: $FLASK_ENV
    depends_on:
      - redis
    ports:
      - "5555:5555"
    command: flower
    networks:
      - default
    volumes:
      - ./build/all/airflow.cfg:/usr/local/airflow/airflow.cfg

  scheduler:
    container_name: airflow-scheduler
    build:
      context: ./build/all
    image: openeo-airflow-all:$AIRFLOW_VERSION
    restart: always
    depends_on:
      - webserver
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      REDIS_PASSWORD: $REDIS_PASSWORD
      LOAD_EX: $LOAD_EX
      FERNET_KEY: $FERNET_KEY
      EXECUTOR: $EXECUTOR
      FLASK_ENV: $FLASK_ENV
    volumes:
      - $PLUGINS:/usr/local/airflow/plugins
      - $AIRFLOW_DAGS:/usr/local/airflow/dags
      - $LOG_DIR_AIRFLOW:/usr/local/airflow/logs
      - ./build/all/airflow.cfg:/usr/local/airflow/airflow.cfg
    command: scheduler
    networks:
      - default

  worker-eodatareaders:
    container_name: airflow-worker-eodatareaders
    build:
      context: ./build/eodatareaders
    image: openeo-airflow-worker-eodatareaders:$AIRFLOW_VERSION
    restart: always
    depends_on:
      - scheduler
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      REDIS_PASSWORD: $REDIS_PASSWORD
      LOAD_EX: $LOAD_EX
      FERNET_KEY: $FERNET_KEY
      EXECUTOR: $EXECUTOR
      GDAL_VRT_ENABLE_PYTHON: $GDAL_VRT_ENABLE_PYTHON
      GDAL_VRT_PYTHON_TRUSTED_MODULES: $GDAL_VRT_PYTHON_TRUSTED_MODULES
      FLASK_ENV: $FLASK_ENV
      OPENEO_PYTHON_UDF_URL: $OPENEO_PYTHON_UDF_URL
      OPENEO_R_UDF_URL: $OPENEO_R_UDF_URL
      OEO_CSW_SERVER: $OEO_CSW_SERVER  # needed by eodc-bindings
      OEO_CSW_SERVER_DC: $OEO_CSW_SERVER_DC  # needed by eodc-bindings
      AIRFLOW_DAGS: /usr/local/airflow/dags
    volumes:
      - $PLUGINS:/usr/local/airflow/plugins
      - $AIRFLOW_DAGS:/usr/local/airflow/dags
      - $HOST_INPUT:$CONTAINER_INPUT
      - files-data:$CONTAINER_OUTPUT
      - $LOG_DIR_AIRFLOW:/usr/local/airflow/logs
      - ./build/eodatareaders/airflow.cfg:/usr/local/airflow/airflow.cfg
    command: worker -q process
    networks:
      - default

  worker-sensor:
    container_name: airflow-worker-sensor
    build:
      context: ./build/sensor
    image: openeo-airflow-worker-sensor:$AIRFLOW_VERSION
    restart: always
    depends_on:
      - scheduler
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      REDIS_PASSWORD: $REDIS_PASSWORD
      LOAD_EX: $LOAD_EX
      FERNET_KEY: $FERNET_KEY
      EXECUTOR: $EXECUTOR
    volumes:
      - $PLUGINS:/usr/local/airflow/plugins
      - $AIRFLOW_DAGS:/usr/local/airflow/dags
      - $HOST_INPUT:$CONTAINER_INPUT
      - files-data:$CONTAINER_OUTPUT
      - $LOG_DIR_AIRFLOW:/usr/local/airflow/logs
      - ./build/sensor/airflow.cfg:/usr/local/airflow/airflow.cfg
    command: worker -q sensor
    networks:
      - default

volumes:
  files-data:
    external:
      name: ${PROJECT_NAME}-${OPENEO_VERSION}-files-data
