"""empty message

Revision ID: 45eddc426037
Revises: 
Create Date: 2018-02-06 15:32:09.742523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45eddc426037'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('git_uri', sa.String(length=128), nullable=False),
    sa.Column('git_ref', sa.String(length=128), nullable=False),
    sa.Column('process_type', sa.String(length=128), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processes')
    # ### end Alembic commands ###
