"""empty message

Revision ID: 95180b904e22
Revises: 45eddc426037
Create Date: 2018-02-28 09:47:21.754501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95180b904e22'
down_revision = '45eddc426037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processes', sa.Column('git_dir', sa.String(length=128), nullable=True))
    op.alter_column('processes', 'git_ref',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('processes', 'git_uri',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processes', 'git_uri',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('processes', 'git_ref',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('processes', 'git_dir')
    # ### end Alembic commands ###
