# This workflow will install Python dependencies, run tests, lint and do static type analysis using nox
# Each microservice is tested by its own job

name: Micorservice Unittests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  capabilities:
    name: Capabilities-Service
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install nox
      run: pip install nox==2020.5.24
    - name: Test with nox
      run: cd services/capabilities && nox

  data:
    name: Data-Service
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install nox
        run: pip install nox==2020.5.24
      - name: Test with nox
        run: cd services/data && nox


  files:
    name: Files-Service
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install nox
        run: pip install nox==2020.5.24
      - name: Test with nox
        run: cd services/files && nox

  processes:
    name: Processes-Service
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install nox
        run: pip install nox==2020.5.24
      - name: Test with nox
        run: cd services/processes && nox

  jobs:
    name: Jobs-Service
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install nox
        run: pip install nox==2020.5.24
      - name: Test with nox
        run: cd services/jobs && nox
