# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Micorservice Unittests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  capabilities:
    name: Capabilities-Service
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6]
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r services/capabilities/requirements.txt
        pip install -r services/capabilities/requirements-test.txt
    - name: Test with pytest
      run: |
        pytest services/capabilities/tests

  files:
    name: Files-Service
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/files/requirements.txt
          pip install -r services/files/requirements-test.txt
      - name: Test with pytest
        run: |
          pytest services/files/tests

  processes:
    name: Processes-Service
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/processes/requirements.txt
          pip install -r services/processes/requirements-test.txt
      - name: Test with pytest
        run: |
          pytest services/processes/tests

  jobs:
    name: Jobs-Service
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/jobs/requirements.txt
          pip install -r services/jobs/requirements-test.txt
      - name: Test with pytest
        run: |
          pytest services/jobs/tests
