name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend_setup:
    name: Setup complete Backend
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Copy env vars
      run: cp -r sample-envs envs && cp sample.env .env
    - name: Create local folders
      run: source .env && chmod 700 setup_scripts/create_local_dirs.sh && setup_scripts/create_local_dirs.sh
    - name: Copy openapi.yml
      run: cp gateway/sample_openapi.yaml gateway/openapi.yaml
    - name: Create docker network
      run: docker network create openeo-v1.0
    - name: Bring up docker-compose
      run: docker-compose up -d
    - name: Wait 1 minute for the docker-compose
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'
    - name: Check containers are running
      run: docker ps

    - name: Export Setup env variables
      run: source setup_scripts/sample-auth.sh
    - name: Initialise databases
      run: chmod 700 setup_scripts/init_dbs.sh && setup_scripts/init_dbs.sh
    - name: Add initial database users
      run: chmod 700 setup_scripts/add_init_users.sh && setup_scripts/add_init_users.sh
    - name: Fill processes and collections
      run: python scripts/add_collections_and_processes.py

