DB_URIS:
    !env_var "processes:Base": postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST:127.0.0.1}:${DB_PORT}/${DB_NAME}

AMQP_URI: !env_var "pyamqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_HOST:127.0.0.1}:${RABBIT_PORT}"
